### ISSUE TITLE
Missing dependencies for cuspn: spn

### ISSUE THREAD

**Issue by yanxp** [ZhouYanzhao/SPN#3]
When run ./install.sh meet the problem:
 note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/spn.dir/init.c.o] Error 1
make[1]: *** [CMakeFiles/spn.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
rm: cannot remove ‘./build’: No such file or directory

Missing dependencies for cuspn:
spn

**Comment by ZhouYanzhao** [comment]
@yanxp , spn package should have been installed before cuspn:
https://github.com/ZhouYanzhao/SPN/blob/96deb3ee84c6325a72f118629f3b01f050331bd8/install/install.sh#L7

1. Have you tried the easy install script?
```bash
# execute this line in you shell
# or you can download the script and run it manually
wget -O - https://git.io/v5wTS | bash
```
2. Have you tried to upgrade Torch to the latest version and reinstall everything?
```bash
# make sure no error appears during the upgration
cd $TORCH_INSTALL_DIR
bash update.sh
# check whether the top commit id starts with "481c50613"
git log
```
3. Have you tried to compile spn and cuspn package manually?
```bash
# compile spn first
cd SPN.torch/install/spn
luarocks make spn-scm-1.rockspec
# then cuspn
cd SPN.torch/install/cuspn
luarocks make cuspn-scm-1.rockspec
```

If none of these works, please post the complete output of the easy install script for debugging.

**Comment by yanxp** [comment]
Alway with the problem:
In file included from /home/d302/torch/install/include/TH/TH.h:4:0,
                 from /home/d302/SPN.torch/install/spn/init.c:1:
/home/d302/torch/install/include/TH/THGeneral.h:65:1: warning: C++ style comments are not allowed in ISO C90 [enabled by default]
 // this hook should only be called by custom allocator functions
 ^
/home/d302/torch/install/include/TH/THGeneral.h:65:1: warning: (this will be reported only once per input file) [enabled by default]
/home/d302/torch/install/include/TH/THGeneral.h:72:17: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define THError(...) _THError(__FILE__, __LINE__, __VA_ARGS__)
                 ^
/home/d302/torch/install/include/TH/THGeneral.h:74:19: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define THCleanup(...) __VA_ARGS__
                   ^
/home/d302/torch/install/include/TH/THGeneral.h:76:20: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define THArgCheck(...)                                               \
                    ^
/home/d302/torch/install/include/TH/THGeneral.h:81:51: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define THArgCheckWithCleanup(condition, cleanup, ...)                \
                                                   ^
/home/d302/torch/install/include/TH/THGeneral.h:94:26: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define THAssertMsg(exp, ...)                                         \
                          ^
In file included from /home/d302/torch/install/include/TH/TH.h:8:0,
                 from /home/d302/SPN.torch/install/spn/init.c:1:
/home/d302/torch/install/include/TH/THLapack.h:8:41: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define THLapackCheck(fmt, func, info , ...)      \
                                         ^
/home/d302/torch/install/include/TH/THLapack.h:15:61: warning: anonymous variadic macros were introduced in C99 [-Wvariadic-macros]
 #define THLapackCheckWithCleanup(fmt, cleanup, func, info , ...)    \
                                                             ^
In file included from /home/d302/torch/install/include/TH/TH.h:12:0,
                 from /home/d302/SPN.torch/install/spn/init.c:1:
/home/d302/torch/install/include/TH/THVector.h:13:8: warning: C++ style comments are not allowed in ISO C90 [enabled by default]
 #endif // TH_VECTOR_INC
        ^
/home/d302/torch/install/include/TH/THVector.h:13:8: warning: (this will be reported only once per input file) [enabled by default]
In file included from /home/d302/torch/install/include/TH/TH.h:15:0,
                 from /home/d302/SPN.torch/install/spn/init.c:1:
/home/d302/torch/install/include/TH/THSize.h:7:1: warning: C++ style comments are not allowed in ISO C90 [enabled by default]
 // THTensor functions that would work on a THSize if we had such a class in C++,
 ^
/home/d302/torch/install/include/TH/THSize.h:7:1: warning: (this will be reported only once per input file) [enabled by default]
In file included from /home/d302/torch/install/include/TH/TH.h:16:0,
                 from /home/d302/SPN.torch/install/spn/init.c:1:
/home/d302/torch/install/include/TH/THStorage.h:29:1: warning: C++ style comments are not allowed in ISO C90 [enabled by default]
 // Given the sizes of {2,N} tensors, write out the size when the tensors are expanded together.
 ^
/home/d302/torch/install/include/TH/THStorage.h:29:1: warning: (this will be reported only once per input file) [enabled by default]
In file included from /home/d302/torch/install/include/lua.h:16:0,
                 from /home/d302/torch/install/include/luaT.h:7,
                 from /home/d302/SPN.torch/install/spn/init.c:2:
/home/d302/torch/install/include/luaconf.h:567:35: warning: C++ style comments are not allowed in ISO C90 [enabled by default]
 #define getlocaledecpoint() ('.') //Code-monkey style
                                   ^
/home/d302/torch/install/include/luaconf.h:567:35: warning: (this will be reported only once per input file) [enabled by default]
/home/d302/SPN.torch/install/spn/init.c: In function ‘luaopen_libspn’:
/home/d302/SPN.torch/install/spn/init.c:15:19: error: ‘LUA_GLOBALSINDEX’ undeclared (first use in this function)
   lua_setfield(L, LUA_GLOBALSINDEX, "spn");
                   ^
/home/d302/SPN.torch/install/spn/init.c:15:19: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/spn.dir/init.c.o] Error 1
make[1]: *** [CMakeFiles/spn.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
rm: cannot remove ‘./build’: No such file or directory

Missing dependencies for cuspn:
spn 


Error: Could not satisfy dependency: spn 
Done!

**Comment by ZhouYanzhao** [comment]
@yanxp ,
It seems to be a Lua52 compatibility issue. Please try the following script and post the output:
```bash
cd ./SPN.torch/install/spn
# clean
rm -r build
# omit LUA_GLOBALSINDEX
sed -i '/lua_setfield/c\  lua_setglobal(L, "spn");' init.c
# reinstall
luarocks make spn-scm-1.rockspec
```

**Comment by yanxp** [comment]
I can train it now. Would you provide the script to locate the bounding box or would you provide the Caffe version?Thanks

**Comment by ZhouYanzhao** [comment]
@yanxp 
* I am glad your installation problem is resolved. It would be nice if you could leave some feedback to someone else who might have similar problems.
* Sorry, we are kinda busy these days, and we don't have time to clean the code. You can easily implement it yourself based on the [paper](https://arxiv.org/pdf/1709.01829) and the [point localization demo](https://github.com/ZhouYanzhao/SPN/blob/torch/demo/notebooks/vis.ipynb).
* Caffe version is under testing (#2). You can get instant email notification once we update by [watching this repo](https://github.com/ZhouYanzhao/SPN/subscription)

**Comment by ZhouYanzhao** [comment]
Closed as the problem was resolved.
