### ISSUE TITLE
cuda runtime error (10) : invalid device ordinal

### ISSUE THREAD

**Issue by JingyunLiang** [ZhouYanzhao/SPN#4]
When training Train_PASCAL.sh, I came across

 "cuda runtime error (10) : invalid device ordinal at /home/daisy/torch/extra/cutorch/init.c:719"

However, I run other codes with no such problem. BTW, I have one Nivida GPU with cuda8.0 on Ubuntu14.04.

**Comment by ZhouYanzhao** [comment]
@MichaelLiang12, the demo uses 4 gpu devices by default. You can modify [this line](https://github.com/ZhouYanzhao/SPN/blob/torch/demo/scripts/Train_PASCAL.sh#L29) to fit your hardware.

**Comment by JingyunLiang** [comment]
Thank you. I'm not familiar with torch's structure.
