### ISSUE TITLE
How to set layerwise learning rates?

### ISSUE THREAD

**Issue by JingyunLiang** [ZhouYanzhao/SPN#5]
I tried to use your model in a totally different dataset, thus I need different learning rates for different layers. I found no way to achieve that. It seems that torch7 is out-of-date and there are few resources about it. 

Though not very relevant to your project, could you tell how to set layerwise learning rates based on your demo? 

Thanks a lot!

**Comment by ZhouYanzhao** [comment]
@MichaelLiang12, for torch version, you can try [this one](https://github.com/gpleiss/nnlr). The [pytorch version](https://github.com/yeezhu/SPN.pytorch) of SPN is also available now :)

**Comment by JingyunLiang** [comment]
Thank you, the pytorch version seems to be more friendly.
