### ISSUE TITLE
Release codes for generating bounding box and corloc evaluation

### ISSUE THREAD

**Issue by zhangyuygss** [ZhouYanzhao/SPN#7]
Could you please release codes for generating bounding box and corloc evaluation?

**Comment by SunSet0864** [comment]
Of course, I have found that some methods which use heatmaps to generate bounding boxes usually don't release their codes in these parts including CAM and this one, so I am curious that maybe methods of generating boxes are the crucial parts in these papers or they actually don't work.

**Comment by ZhouYanzhao** [comment]
@zhangyuygss @sirius64 
My apologies for the delay. Considering that Torch7 is a bit out-of-date, we have released the BBox generation as well as the evaluation codes in the [PyTorch version](https://github.com/yeezhu/SPN.pytorch). Feel free to ping me (yzhou.work at outlook.com) directly if you need further help.
